### ISSUE TITLE
cocos2d: warning: Uniform not found: u_texture

### ISSUE THREAD

**Issue by alfogrillo** [namkazt/NewDynamicLight#1]
Hi namkatzt
First thank you for your patch! :-)
The code works with the latest version of cocos2d-x (cocos2d-x 3.11)!
However I noticed that in your test project the following warning shows when "light" is moved with mouse:

`cocos2d: warning: Uniform not found: u_texture
`

Any clue about this?

**Comment by namkazt** [comment]
i will check it when have time. thank you

**Comment by alfogrillo** [comment]
Thanks!

I noticed also that shadows have some problem on iOS: if you place a simple shadow caster (as the cocos2d-x logo), you will notice a fake radial shadow starting at 180 degrees.
The problem is not present on Android 5.1 and Linux.
